version: 2

models:
  - name: dim_accounts
    description: "Dimension table containing accounts details"
    columns:
      - name: account_key
        description: "Primary key for accounts"
        tests:
          - not_null
          - unique

  - name: dim_products
    description: "Dimension table containing products details"
    columns:
      - name: product_key
        description: "Primary key for products"
        tests:
          - not_null
          - unique

  - name: dim_salesteams
    description: "Dimension table containing sales teams details"
    columns:
      - name: sales_agent_key
        description: "Primary key for sales agents"
        tests:
          - not_null
          - unique

  - name: fact_salespipeline
    description: "Fact table for sales opportunities"
    columns:
      - name: opportunity_id
        description: "Primary key for the fact table"
        tests:
          - not_null
          - unique

      - name: account_key
        description: "Foreign key to dim_accounts"
        tests:
          - relationships:
              arguments:
                to: ref('dim_accounts')
                field: account_key

      - name: product_key
        description: "Foreign key to dim_products"
        tests:
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_key
          
      - name: sales_agent_key
        description: "Foreign key to dim_salesteams"
        tests:
          - relationships:
              arguments:
                to: ref('dim_salesteams')
                field: sales_agent_key
